version: '3'

services:
    postgres:
        image: postgres
        ports:
            - '5431:5432'
        environment:
            POSTGRES_USER: backend
            POSTGRES_PASSWORD: let-me-in
            POSTGRES_DB: database
